"""initial

Revision ID: 2dfe4849a294
Revises:
Create Date: 2026-04-11 22:02:57.990798

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import pgvector
import app

# revision identifiers, used by Alembic.
revision: str = "2dfe4849a294"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ministries",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("short_name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ministries_name"), "ministries", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("middle_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("SUPERUSER", "ADMIN", "USER", name="user_role"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "conversations",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column(
            "pinned_document_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "CONSTITUTION",
                "ACT",
                "REGULATION",
                "AMENDMENT",
                "ORDINANCE",
                "GUIDELINE",
                "OTHER",
                name="document_category",
            ),
            nullable=False,
        ),
        sa.Column(
            "language", sa.Enum("ENGLISH", "NEPALI", name="language"), nullable=False
        ),
        sa.Column("ministry_id", sa.UUID(), nullable=True),
        sa.Column("domain", sa.String(length=100), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "READY", "FAILED", name="document_status"),
            nullable=False,
        ),
        sa.Column("celery_task_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ministry_id"], ["ministries.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_hash", name="uq_file_hash"),
    )
    op.create_index(
        op.f("ix_documents_ministry_id"), "documents", ["ministry_id"], unique=False
    )
    op.create_index(op.f("ix_documents_status"), "documents", ["status"], unique=False)
    op.create_table(
        "messages",
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("USER", "ASSISTANT", "SYSTEM", name="message_role"),
            nullable=False,
        ),
        sa.Column(
            "source_chunks", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_conversation_id"),
        "messages",
        ["conversation_id"],
        unique=False,
    )
    op.create_table(
        "parent_chunks",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column(
            "chunk_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_parent_chunks_document_id"),
        "parent_chunks",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "child_chunks",
        sa.Column("parent_id", sa.UUID(), nullable=False),
        sa.Column("content", app.db.column.bm25.BM25Text(), nullable=False),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False
        ),
        sa.Column(
            "chunk_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["parent_chunks.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_child_chunks_content_bm25_english",
        "child_chunks",
        ["content"],
        unique=False,
        postgresql_using="bm25",
        postgresql_with={"text_config": "english"},
        postgresql_where=sa.text("language = 'en'"),
    )
    op.create_index(
        "ix_child_chunks_content_bm25_nepali",
        "child_chunks",
        ["content"],
        unique=False,
        postgresql_using="bm25",
        postgresql_with={"text_config": "nepali"},
        postgresql_where=sa.text("language = 'ne'"),
    )
    op.create_index(
        "ix_child_chunks_embedding_diskann",
        "child_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="diskann",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={
            "num_neighbors": 50,
            "search_list_size": 100,
            "max_alpha": 1.2,
        },
    )
    op.create_index(
        op.f("ix_child_chunks_parent_id"), "child_chunks", ["parent_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_child_chunks_parent_id"), table_name="child_chunks")
    op.drop_index(
        "ix_child_chunks_embedding_diskann",
        table_name="child_chunks",
        postgresql_using="diskann",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={
            "num_neighbors": 50,
            "search_list_size": 100,
            "max_alpha": 1.2,
        },
    )
    op.drop_index(
        "ix_child_chunks_content_bm25_nepali",
        table_name="child_chunks",
        postgresql_using="bm25",
        postgresql_with={"text_config": "nepali"},
        postgresql_where=sa.text("language = 'ne'"),
    )
    op.drop_index(
        "ix_child_chunks_content_bm25_english",
        table_name="child_chunks",
        postgresql_using="bm25",
        postgresql_with={"text_config": "english"},
        postgresql_where=sa.text("language = 'en'"),
    )
    op.drop_table("child_chunks")
    op.drop_index(op.f("ix_parent_chunks_document_id"), table_name="parent_chunks")
    op.drop_table("parent_chunks")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_documents_status"), table_name="documents")
    op.drop_index(op.f("ix_documents_ministry_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_ministries_name"), table_name="ministries")
    op.drop_table("ministries")
    # ### end Alembic commands ###
