"""removed reverse relationship

Revision ID: 6091c50a1f22
Revises: 2dfe4849a294
Create Date: 2026-04-17 19:38:32.975574

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "6091c50a1f22"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "2dfe4849a294"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
