#!/bin/bash

psql -v ON_ERROR_STOP=1 <<-EOSQL
   CREATE USER $DATABASE__USER WITH PASSWORD '$DATABASE__PASSWORD';
   CREATE DATABASE $DATABASE__NAME OWNER $DATABASE__USER;
   GRANT ALL PRIVILEGES ON DATABASE $DATABASE__NAME to $DATABASE__USER;
   ALTER ROLE $DATABASE__USER WITH LOGIN;
   ALTER ROLE $DATABASE__USER WITH CREATEDB;
EOSQL

# Install pgvector extension
psql -v ON_ERROR_STOP=1 -d $DATABASE__NAME <<-EOSQL
   CREATE EXTENSION IF NOT EXISTS citext;
   CREATE EXTENSION IF NOT EXISTS vector;
   CREATE EXTENSION IF NOT EXISTS vectorscale CASCADE;
   CREATE EXTENSION IF NOT EXISTS pg_textsearch;
   CREATE EXTENSION IF NOT EXISTS pg_trgm;
EOSQL
