#!/bin/bash

psql -v ON_ERROR_STOP=1 <<-EOSQL
   CREATE USER $SETTINGS_DB_USER WITH PASSWORD '$SETTINGS_DB_PASSWORD';
   CREATE DATABASE $SETTINGS_DB_NAME OWNER $SETTINGS_DB_USER;
   GRANT ALL PRIVILEGES ON DATABASE $SETTINGS_DB_NAME to $SETTINGS_DB_USER;
   ALTER ROLE $SETTINGS_DB_USER WITH LOGIN;
   ALTER ROLE $SETTINGS_DB_USER WITH CREATEDB;
EOSQL

# Install pgvector extension
psql -v ON_ERROR_STOP=1 -d $SETTINGS_DB_NAME <<-EOSQL
   CREATE EXTENSION IF NOT EXISTS vector;
   CREATE EXTENSION IF NOT EXISTS vectorscale CASCADE;
   CREATE EXTENSION IF NOT EXISTS pg_textsearch;
   CREATE EXTENSION IF NOT EXISTS pg_trgm;
EOSQL
